---
bibliography: references.bib
---

\normalsize

# Discussion

The present study offers new insights into new-onset delirium in the largest stroke cohort investigating delirium to date, emphasizing the significant role of biological sex and various clinical factors in its occurrence. It integrates a wide range of variables—including demographics, clinical presentations, therapeutic interventions, and medications—and applies Bayesian methodology in an open source code approach. Furthermore, it highlights the importance of studying delirium in stroke patients demonstrating its relevance for short-term, surrogate, and long-term functional outcomes.

*Occurrence of delirium and sex differences*

Delirium occurred in 6.3% of patients in this study, with a notably higher incidence in males (7.3%) compared to females (4.8%). This significant sex difference persisted even after adjusting for confounding factors such as age and stroke severity, with male sex remaining an independent predictor of delirium (odds ratio 2.1, 95% credible interval 1.68–2.66). These findings challenge the results from a previous meta-analysis on vascular risk factors contributing to delirium, where Siokas and colleagues found sex to be no independent factor predicting delirium (odds ratio 0.98, 95% confidence interval 0.87--1.11). [@siokas2022] It aligns with research on non-stroke patients, where postoperatively males undergoind non-cardiac surgery were found to be at an increased risk for developing postoperative delirium [@wittmann2022], whereas other studies in cardiac patients found female subjects to be at a greater risk. [@saczynski2012] The implications of this finding are important for further research. Recognizing a difference of risk factor for delirium in biological sex may allow targeted monitoring and individual preventive strategies for males and females, potentially reducing the incidence and severity of delirium.

*Age and its interaction with sex*

The study demonstrated a meaningful association between age and the occurrence of delirium, with older patients exhibiting a higher probability of developing delirium. This is consistent with the well-established understanding that advanced age is a major risk factor for delirium due to age-related physiological changes, increased comorbidities, and decreased cognitive reserve. [@inouye2014] Notably, the interaction between age and sex revealed that females between the ages of 70 and 90 were less likely to develop delirium compared to their male counterparts. This suggests that the potentially protective circumstances in stroke patients associated with female sex may become more pronounced with advancing age. Further data to compare with are sparse, however in a general population one Polish study addressed that males under 65 are more prone to delirium than females in that age group, and above 85 this is reported to be reversed with higher odds of delirium in females [@serpytis2017]. Overall, most studies report age and sex separately as non-modifyable risk factors of delirium [@fong2009]. The present study, therefore adds to this body of knowledge by highlighting the need for sex-specific approaches to delirium prevention while considering age specific groups.

*Premorbid function*

The premorbid Rankin Scale (pRS) was used to assess the relationship between pre-stroke functional status and delirium occurrence. Contrary to expectations, none of the pRS levels showed a convincing association with delirium. This finding differs from previous research that has identified poor premorbid functional status as an independent risk factor for delirium [@pasinska2018; @kotfis2019]. One possible explanation is the relatively low number of patients in the higher pRS categories in this study, which may have limited the statistical power for detection. Another explanation may be the high number of included variables in this study that may have sufficiently explained potential premorbid disability.

*Stroke severity, location, aphasia, and neglect*

As anticipated, higher National Institutes of Health Stroke Scale (NIHSS) scores, indicating more severe strokes, were strongly associated with an increased probability of delirium (odds ratio 1.456). This aligns with existing literature, as severe strokes are more likely to result in extensive brain damage, increased intracranial pressure, and a greater burden of neurological deficits, all of which can contribute to delirium. Furthermore, strokes in the right hemisphere and posterior circulation were linked to a higher likelihood of delirium compared to left hemispheric strokes. Right hemispheric strokes can affect attentional networks and spatial awareness, potentially leading to neglect and confusion. However, this contradicts a recent meta-analysis which found that stroke side was not associated with delirium when comparing right to left (RR 0.99, CI 0.77-1.28) [@rhee2022] Interestingly, a recent small study investigating brain network dysfunction in patients with stroke that experienced delirium found a cortico-subcortical hemispheric connectivity to be imbalanced. Future studies on this topic may improve using a more granular approach for lesion detection to identify lesion specific differences within hemispheres between the sexes.

Interesting in this context was the investigation of cortical lesion syndromes such as aphasia and inattention/neglect in this cohort. While aphasia showed no main effect associations with delirium, a moderation by sex demonstrated males with moderate to severe aphasia to develop delirium much more likely than women. Comparing neglect syndromes showed that presence of neglect in stroke patients per se more likely leading to delirium. There were also strong hints for a specific vulnerability of women for delirium when experiencing isolated visual neglect. This may be of interest as sex differences in the representation of visuospatial functions are discussed since the early 1990s, hypothesizing that visuospatial functions is bilaterally represented in brains of men versus a right sided representation in women. [@desmond1994; @halpern2005] This may result in differences of impairments although lesions are comparable.

*Temporal influence and therapy modes*

Covering a time span over more than 20 years, this study shows a clear increase of delirium occurrence over time. This may be accounted to several aspects considering increased screening rates and more awareness, but also intensification of the therapy of acute ischemic stroke. For example, as demonstrates earlier, with the increase in numbers of patients with intravenous thrombolysis from 2000 to 2010, delirium also increased. In addition, a clear increase of patients can be found in patients that underwent endovascular therapies from 2014 onwards. This likely reflects the increased numbers of patients treated with endovascular therapy from the time randomized controlled trials showed a most beneficial effect in this field. Likewise to cardiac and non-cardiac surgery, one could speculate about the potential of the intervention or procedure itself that may provoke delirium. However, when considering other confounders in a multivariable model including early prognostic factors, mode of therapy did not have crucial influence in explaining occurrence of delirium.

*Cerebral small vessel disease and prestroke dementia*

Other factor that are generally known to influence delirium are presence of cerebral small vessel disease [@clancy2021] and diagnosis of dementia [@hénon1999; @fong2022]. It was therefore rather expected that these factor also play an important role in predicting delirium when stroke happens. Females had a higher frequency of severe small vessel disease, which may be due to a longer lifespan, hormonal influences, or comorbidities like hypertension and diabetes. While there was no difference between patients having 'no' compared to 'minor' small vessel disease in the risk of delirium, moderate and severe small vessel disease showed a steady increase of risk. From a viewpoint of pathophysiology the link between cerebral small vessel disease and delirium is resonable, both involving endothelial dysfunction, blood-brain-barrier breakdown, and inflammation. [@gao2022; @maclullich2008; @wilson2020] The expected finding may understate the relevance of this cohort being a representative stroke cohort for delirium.

For dementia, prevalence of pre-stroke dementia is reported with 9% and 14% in population-based studies and hospital-based studies, respectively [@pendlebury2009] In this study, pre-existing dementia was more frequent in females (5.5%) than males (2.8%), and having a previous diagnosis of dementia increased the likelihood of developing delirium (odds ratio 1.92). This is consistent with research indicating that pre-existing cognitive impairment is a strong predictors of delirium [@inouye2014]. Because this was a hospital-based study this low percentage may be due the retrospective nature, where only established dementia diagnosis at admission were identified. This more narrow selection may on the other hand be the reason, why pre-existing dementia persisted as independent predictor even in multivariable analysis with high probability. In the sex-specific interaction, an interesting pattern between females and males was observed. In patients without pre-existing dementia before the stroke, females had an advantage for protection against a delirium as compared to males. However, this advantage disappeared if the patient already had dementia before the stroke. (In both males and females, having pre-stroke dementia increased the likelihood of developing delirium.)

*Level of consciousness and delirium*

Reduced levels of consciousness at admission, such as somnolence, sopor, and coma, were associated with a higher likelihood of developing delirium. A reduced level of consciousness involves impairment of attention and awareness, which are also hallmarks of delirium. A disruption of information processing and the sleep-wake cycle, overall immobilization or even medical restrain may result, which further contributes to delirium. Underlying causes of reduced consciousness may involve not only stroke itself, but conditions such as an already reduced cognitive reserve, metabolic disturbances, or ongoing infections. Altered consciousness usually demands giving sedatives for diagnostic and therapy approaches, which may also have deliriogenic effects. [@dostovic2018; @klimiec2017; @klimiec2016]

The higher the impairment of conciousness, the more susceptible females may be for delirium as demonstrated in the interaction of sex and level of consciousness in their relationship to occurrence of delirium. A differential response depending on biological sex for the potential risk of delirium is a challenging new hypothesis and needs further studying.

*Medication*

This study identified several medications (groups and substances) that were associated with either an increased or decreased risk of delirium in stroke patients. Also, interesting differences between males and females became apparant.

Rather unexpected was the finding of Angiotensin II Receptor Blockers (ARBs) to have a strong association with delirium risk (OR 1.60, 95% CI 1.14-2.20). Findings on a substance level were in concordance where valsartan and candesartan showed associations in the same direction. ARBs act by blocking the angiotensin II type 1 (AT1) receptor, which is part of the renin-angiotensin system (RAS), and, overall, ARBs are considered to have protective effects. Neuroprotection in this regard is discussed to involve a reduction of neuroinflammation [@benicky2009], the protection of cerebral blood flow and autoregulation [@nishimura2000], mitochondrial protection [@khoury2012], and the reduction of oxidative stress [@danielyan2007]. [@villapol2015] ARBs also take action modulating the neurotransmitter system the noradrenergic and cholinergic systems. The latter is a well established factor for delirium risk, especially. [@carter1996]

Considering the overlap in mechanisms influenced by ARBs, the likely influence on delirium risk may not seem far fetched. Contradictory to findings in this study, in a secondary analysis of patients from two randomized trials in an intensive care unit setting, pre-admission use of ARBs was not associated with a significant increase in delirium risk [@mulkey2023]. Another single centre experience over five years in postoperative delirium risk found no difference in patients taking ARBs pre-operatively compared to those who did not. Interestingly, delirium risk was reduced in patients using ARBs postoperatively (odds ratio 0.55 (95% CI, 0.43 to 0.72). Because mentioned studies did not include patients suffering from stroke, the cohorts are not directly comparable. However, it may suggest that possible protection of ARBs is alleviated or even reversed when stroke patients are not continued on this medication for reasons such as acute interventions, dysphagia, or simply because the pre-medication is not known. Other mechanisms may involve new drug-drug interactions during hospitalisation or a pathyphysiology involving ARBs that is specific to stroke patients.

The pyrazolones class, including the substance metamizole, showed associations with increased delirium risk (odds ratio 1.354). Pyrazolones have analgesic properties but may cause central nervous system side effects when exhibiting hypotension (especially when administered intravenously). These sudden drops in blood pressure could lead to hypoperfusion and therefore promote delirium. [@kötter2015] While the exact mechanisms are yet to be elucidated, metamizole has been reported to cause psychiatric side effects, including confusion. [@DAE50384a]

Other Antiepileptics (ATC code N03AX) including pregabalin and gabapentin were associated with increased delirium risk (odds ratio 1.832) as group effect, but also the individual substances. Overall, possible reasons may include their effects on the neurotransmitter systems and sedation. Pregabalin - a GABA analog - is commonly prescribed for treating neuropathic pain and other conditions. Several reports have associated pregabalin with delirium and confusional states. Aside from increased delirium risk in high-dose pregabalin therapies, this may be particularly the case when discontinued abruptly. [@olaizola2006; @ishikawa2021]. In one study analysing the French Pharmacovigilance Database the authors reported mainly neuropsychiatric adverse drug reactions in 608 cases for pregabalin and 725 for gabapentin. Gabapentin was also associated with increased delirium in this study. The mechanism of action of gabapentin is the alpha-2-delta subunit of calcium channels in the central and peripheral nervous system. Common side effects include visual disturbance, dizziness, and confusion aside from a sedative effect. [@gajraj2007; @thefrenchnetworkofpharmacovigilancecentres2013]. Therefore this finding doesn't come surprising and is further supported by a study investigating perioperative use of gabapentin in older adults undergoing major surgery with gabapentin users having an significant increased risk of delirium (risk ratio, 1.28 \[95% CI, 1.23-1.34\]). [@park2022]

For some medications in this study potential protective association were found. On the group level glucocorticoids were associated with a decreased risk of delirium. This may contradict the known common adverse drugs effects of glucocorticoids causing neuropsychiatric side effects. However, pre-admission glucocorticoids were unlikely to be given in high dosages, but rather as long term medications or tampering medication in (chronic) inflammatory processes. These anti-inflammatory mechanisms may also be one possible mechanism of action for a potential protection against a delirium reducing cerebral edema and oxidative stress. On a substance level this association could not be validated and results should therefore be interpretated with caution.

*Short and long-term functional outcomes and influence of delirium and sex*

Delirium was strongly associated with short and long-term outcomes, including more extended hospital stay, lower Barthel Index scores and higher NIHSS scores at discharge, higher mortality rates in relation to length of hospital stay, a shift to a higher (worse) category on the mRS, and against a favourable outcome (mRS 0--2). These findings could be confirmed in multivariable analysis, where delirium during hospital stay independently predicted each outcome. As the largest cohort investigating delirium in ischemic stroke patients so far, this confirms the finding of various previous reports demonstrating the adverse impact of delirium on rehabilitation and short- and long-term outcomes [@mcmanus2009; @shi2012]

Several sex differences in these outcomes could be observed. For example, pneumonia as a complication after stroke was more common in males than females (21.0% vs. 14.4%), which compares well to a previous report by the Swedish National Stroke Registry. [@eriksson2009] While pneumonia was an independent predictor of long term outcome, the sex differences in incidences were not observed as being relevant for explaining a shift towards a higher mRS category at 90 days after stroke. On the contrary, sepsis, myocardial infarction and deep vein thrombosis were all significantly associated with a worse outcome for males in multivariable regression when predicting mRS at 90 days. Sex differences in sepsis also reporting a disadvantage for males can be found in recent experimental research [@joaquim2024] and goes along with pathophysiological consideration in sepsis in general [@lakbar2023; @shields2023]. However, data on clinical research on this subtopic in sepsis is sparse. Regarding post-stroke sex differences of myocardial infarction, a recent study in stroke patients defined myocardial injury based on high-sensitive troponin levels and found different odds ratios between the sexes, favouring males with a better functional outcome at discharge. [@rosso2024] Latter study was prospective and may not be directly comparable to this work because of its retrospective nature and a different definition of a clinical diagnosis of myocardial infarction.

As for surrogate and functional outcome, females - despite a comparable median length of stay of four days - showed associations in multivariable analysis towards a shorter stay when trying to explain length in hospital. For short-term (hospital discharge) functional outcomes females experienced lower Barthel-Index scores in every single subcategory (that is a worse performance in every days tasks such as toileting, dressing or ability to climb stairs), but experienced death during hospital stay less likely. Comparable associations for the sexes were seen in multivariable analysis explaining NIHSS at discharge and at 90 days after stroke functional outcome using the mRS. Differences in recovery trajectories may be influenced by biological and immunological factors. Expanding clinical research in this area is crucial to improve understanding and guide targeted interventions for recovery variability.

*Strength and limitation*

The study is retrospective and although it employed a meticulous methodological approach, limitations inherent to this design remain.

Concerning the detection of delirium it is essential to acknowledge that different types of delirium, including hypoactive delirium, may have been underdiagnosed in presented cohort. Furthermore, the overall rate of delirium in this cohort was 6.3%. In a meta-analysis, Zhang and colleagues found significant variability in the occurrence of delirium, ranging from 4.9% to 66.2%. It's worth noting that presented cohort, which was selected based on treatment indication, had a delirium frequency on the lower end of this spectrum. However, results from a very recent report in a severely affected stroke population that is comparable to this population, Sachdev and colleagues retrospectively found a delirium diagnosis in 5.1% of patients.

Cases of delirium might have been misclassified because of inconsistent documentation practices or varying diagnostic criteria used by treating physicians. For instance, different clinicians might have interpreted symptoms of delirium differently, which leads to inconsistencies in case identification. Especially the diagnostic criteria of delirium, although following a standard operating procedure and applying well-known delirium detection scores, may have been variable over the years, may have been specific to teams and individuals. Additionally, factors like nurse-to-patient ratios, hospital environment, and staff awareness and training on delirium recognition can affect the incidence and detection of delirium. Moreover, the study did not assess information on the severity or exact duration of delirium episodes. For future studies, this may be most important for a better understanding of how delirium impacts outcome.

New variables were sourced through a semi-automatic process, which included diagnosis retrieval from the hospital information system and chart retrieval using search terms via regular expressions. Feedback loops were implemented to ensure accuracy, constantly improving the search terms and achieving a high true positive rate. Despite these measures, underdetection and misclassification cannot be entirely ruled out because of potential data entry errors and incorrect coding during chart reviews.

Moreover, the study period spans over 20 years. Over such a long time, changes in clinical practices, diagnostic criteria, and hospital standards and policies could introduce a temporal bias. However, analyses directly show differences in admission years, and admission years are accounted for in Bayesian regression analyses, which ultimately improves interpretability.

The cohort was selected based on specific treatment indications. Selection bias may be present, and the sample may not represent the general population. Additionally, it might exclude certain patient groups, limiting the generalizability of the findings to other settings or populations. Although the Heidelberg stroke center is one of the first established in Germany and known for its high-quality standards, the study is monocentric, and results need external evaluation. The study tried to include many factors associated with delirium; however, unmeasured confounders may exist, which have not been accounted for. Factors such as socioeconomic status, ethnicity, educational background, or unrecorded comorbidities may influence the occurrence of delirium and, ultimately, functional outcomes. This may lead to residual confounding. Unmeasured psychological factors like stress and anxiety can contribute to delirium as well as they are often not recorded in medical records, leading to incomplete risk factor assessment.

Additionally, a pre-stroke decline in cognition that previously did not result in a dementia diagnosis would have gone unnoticed, as only established dementia diagnoses at hospital admission were assessed. However, the finding of preexisting dementia being an independent predictor for many models, speaks for a neglectable bias.

The variable selection process for individual models was based on available evidence from literature reviews and information on associations from univariable or bivariable models. The study actively and openly reports missing data for all variables of interest. Missing data ultimately reduce statistical power and introduce bias if the missingness is not random, as was assumed. To address this potential bias, final models were additionally calculated using multiple imputation datasets.

In this study, the time at which delirium was diagnosed during the hospital stay was unavailable. Therefore, a differentiation between early-onset and late-onset delirium could not be made. Additionally, as for other outcomes that occurred during hospital stay (e.g., pneumonia), associations to delirium can only be made without a clear direction of effect. For this reason, the focus for a delirium model was set on the very early stage at hospital admission. This study collected a great number of medications that were available at hospital admission, focusing on the drug substance itself rather than detailed dosing information. During the hospital stay and thereafter, medications other than recombinant tissue plasminogen activator were not researched - this may limit the interpretability of associations of admission medications with outcomes. This work did not focus on the exact diagnostic workup of stroke patients.

*Summary*

This study retrospectively evaluated biological sex differences in the context of delirium in a large, consecutive cohort of acute ischemic stroke patients who received measures of revascularisation therapy.

-   Delirium occurred in 6.3% of patients, with a higher incidence in males (7.3%) compared to females (4.8%). Biological sex was identified as a significant factor influencing the temporal variability of applied therapies, as well as the interactions between sex, stroke location, and stroke severity. Additionally, age was found to be the most crucial factor affecting stroke distribution differently between the sexes.

-   Male sex was identified as an independent predictor of delirium (odds ratio 2.1, 95% credible interval 1.68–2.66) even after accounting for the most relevant confounders. Several factors predict new delirium during the hospital stay, including age, pre-stroke dementia, and cerebral small vessel disease. However, variables that persisted in a multivariable model were sex, age, year of therapy, neglect, aphasia, and diabetes mellitus. Notably, sex moderated the effects of aphasia, level of consciousness, and admission medications (e.g., pregabalin) on delirium risk.

-   As expected and confirmative to previously published reports, delirium in stroke patients independently influences stroke outcomes. In this study, the following were observed: patients who experienced delirium had a more extended hospital stay, lower Barthel Index scores and higher NIHSS scores at discharge, higher mortality rates in relation to length of hospital stay, a shift to a higher (worse) category on the mRS, and a non-favourable outcome (mRS 3—6).

This study highlights the importance of examining delirium in stroke patients and suggests that biological sex should be considered in individualized treatment approaches. Future research should further explore the role of sex in delirium and evaluate sex-specific treatment strategies in clinical trials.
